FROM ubuntu:22.04

COPY . /root/.eunomia/bin

ENV PATH="/root/.eunomia/bin:${PATH}"

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        clang llvm libelf1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /code

ENTRYPOINT ["ecc-rs"]
