apiVersion: v1
kind: Pod
metadata:
  name: ecli-x86-ubuntu-pod
spec:
  containers:
  - name: ecli-x86-ubuntu
    image: ngccc/ecli_x86_ubuntu
    command: ["/bin/sh","-c","./ecli run /var/ebpfPackage/package.json"]
    volumeMounts:
    - mountPath: /sys/kernel/debug
      name: logs
    - mountPath: /var/ebpfPackage/
      name: config-vol 
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true

  volumes:
  - name: logs
    hostPath: 
      path: /sys/kernel/debug
      type: Directory
  - name: config-vol
    configMap:
      name: ebpf-config

